env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io

before:
  hooks:
  - go mod download

builds:
  main: ./gboil
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm
    - arm64
  ignore:
    - goos: darwin
      goarch: 386
  # Run upx after build finished
  hooks:
    post: ./upx.sh
  overrides:
    ldflags:
      - -s -w

archives:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"  

project_name: gboil-cli

# Check https://goreleaser.com/customization/homebrew/
brews:
  homepage: 'https://github.com/goboiler/homebrew-gboil-cli'
  description: 'gboil-cli homebrew package.'
  folder: Formula
  commit_author:
    name: danecwalker
    email: dane@danecwalker.com
  tap:
    owner: danecwalker
    name: homebrew-gboil-cli