builds:
  - main: ./gboil

project_name: gboil

# Check https://goreleaser.com/customization/homebrew/
brews:
  - homepage: 'https://github.com/goboiler/gboil-cli'
    description: 'gboil-cli homebrew package.'
    folder: Formula
    commit_author:
      name: danecwalker
      email: dane@danecwalker.com
    tap:
      owner: goboiler
      name: gboil-cli