# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gboil < Formula
  desc "gboil-cli homebrew package."
  homepage "https://github.com/goboiler/gboil-cli"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goboiler/homebrew-gboil-cli/releases/download/v0.0.3/gboil_0.0.3_darwin_amd64.tar.gz"
      sha256 "881d092f3f6da88fd6319af4ae31e80f2037f762f4c156704c7177d57a844d79"

      def install
        bin.install "gboil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goboiler/homebrew-gboil-cli/releases/download/v0.0.3/gboil_0.0.3_darwin_arm64.tar.gz"
      sha256 "3e90b8542c4f106b6b8c58e8edf6aa2d0743955fe425c8cc5161f5021038ea74"

      def install
        bin.install "gboil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goboiler/homebrew-gboil-cli/releases/download/v0.0.3/gboil_0.0.3_linux_arm64.tar.gz"
      sha256 "a0c651f7e09ba781837ded8c971dafcc56da2965e8aa06cd59dd2fd2efa1c147"

      def install
        bin.install "gboil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goboiler/homebrew-gboil-cli/releases/download/v0.0.3/gboil_0.0.3_linux_amd64.tar.gz"
      sha256 "2c3feb0aa185dbd9fecde4d1e0c471fc0612003ab20b44b587ff82c694e05c02"

      def install
        bin.install "gboil"
      end
    end
  end
end
