# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gboil < Formula
  desc "gboil-cli homebrew package."
  homepage "https://github.com/goboiler/gboil-cli"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goboiler/homebrew-gboil-cli/releases/download/v0.0.2/gboil_0.0.2_darwin_amd64.tar.gz"
      sha256 "501c62e3945786e8323a055a8c9c0024f3ccb94439dd3ae62df4b693d1f2ad15"

      def install
        bin.install "gboil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goboiler/homebrew-gboil-cli/releases/download/v0.0.2/gboil_0.0.2_darwin_arm64.tar.gz"
      sha256 "6924d0977a35ba0e4be0d603bf52273c98393a3c8fc1c2eea933aa6183889acd"

      def install
        bin.install "gboil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goboiler/homebrew-gboil-cli/releases/download/v0.0.2/gboil_0.0.2_linux_arm64.tar.gz"
      sha256 "f665d4f27405f9f0fed68ab9b2854563c6696ab4e5daa986346ae05908f3b40e"

      def install
        bin.install "gboil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goboiler/homebrew-gboil-cli/releases/download/v0.0.2/gboil_0.0.2_linux_amd64.tar.gz"
      sha256 "fd4e41da0a76c2017e830e207e53e9e85201171147ec853ad3fbce8f567a0996"

      def install
        bin.install "gboil"
      end
    end
  end
end
