# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GboilCli < Formula
  desc "gboil-cli homebrew package."
  homepage "https://github.com/goboiler/homebrew-gboil-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/goboiler/homebrew-gboil-cli/releases/download/v0.0.1/gboil-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "f539142625b935368e8551bd9ca47cee5169fd8d663f3f78b10cb3f6dcd4b8c0"

      def install
        bin.install "gboil-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goboiler/homebrew-gboil-cli/releases/download/v0.0.1/gboil-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "d4644e63c11a9965f02a2d53da78ab9fd58109dcf34adf3b1bc417dd4d2102b8"

      def install
        bin.install "gboil-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/goboiler/homebrew-gboil-cli/releases/download/v0.0.1/gboil-cli_0.0.1_linux_amd64.tar.gz"
      sha256 "f92684072f1349cef950f03c23ad3771e76df619ae37819314d6167ec30d4ad2"

      def install
        bin.install "gboil-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goboiler/homebrew-gboil-cli/releases/download/v0.0.1/gboil-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "33079976045d8873457af3a92173a8327989ee90a224912bf7bfe2851c7dbbab"

      def install
        bin.install "gboil-cli"
      end
    end
  end
end
