# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gboil < Formula
  desc "gboil-cli homebrew package."
  homepage "https://github.com/goboiler/gboil-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/goboiler/gboil-cli/releases/download/v0.0.1/gboil_0.0.1_darwin_amd64.tar.gz"
      sha256 "fa8cb9804600f1ca8a119af4c76a42ed1351ee0d48f50d5a8e2a4a5296cac05c"

      def install
        bin.install "gboil"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/goboiler/gboil-cli/releases/download/v0.0.1/gboil_0.0.1_darwin_arm64.tar.gz"
      sha256 "2ab818c30cf91aa09d4c95d127cc4a901485690f6af282ac43b4acb5d416b16b"

      def install
        bin.install "gboil"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/goboiler/gboil-cli/releases/download/v0.0.1/gboil_0.0.1_linux_arm64.tar.gz"
      sha256 "220e95d3747e0ae4ea45cf29e5780de75d0e11166ea7bde48e1388a018a0c2fc"

      def install
        bin.install "gboil"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/goboiler/gboil-cli/releases/download/v0.0.1/gboil_0.0.1_linux_amd64.tar.gz"
      sha256 "710349404590c77bfaffa362b0add469b0f482862d0d148204033720f5ba82f3"

      def install
        bin.install "gboil"
      end
    end
  end
end
